# Generated by Django 3.0.6 on 2020-06-02 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('idtipo_documento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombredocumento', models.CharField(db_column='nombreDocumento', max_length=45)),
            ],
            options={
                'db_table': 'tipo_documento',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('primernombre', models.CharField(db_column='primerNombre', max_length=45)),
                ('segundonombre', models.CharField(blank=True, db_column='segundoNombre', max_length=45, null=True)),
                ('primerapellido', models.CharField(db_column='primerApellido', max_length=45)),
                ('segundoapellido', models.CharField(blank=True, db_column='segundoApellido', max_length=45, null=True)),
                ('numerodocumento', models.IntegerField(db_column='numeroDocumento', unique=True)),
                ('contrasena', models.CharField(max_length=45)),
                ('fecharegistro', models.DateTimeField(auto_now_add=True, db_column='fechaRegistro', null=True)),
                ('id_tipo_documento', models.ForeignKey(db_column='id_tipo_documento', on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.TipoDocumento')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
