# Generated by Django 3.0.6 on 2020-06-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='ult_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
