# Generated by Django 3.0.8 on 2020-07-22 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20200618_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='id_estado',
            field=models.OneToOneField(db_column='id_estado', on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.EstadosUsuario'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id_tipo_documento',
            field=models.OneToOneField(db_column='id_tipo_documento', on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.TipoDocumento'),
        ),
    ]
