# Generated by Django 2.1.15 on 2020-08-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20200722_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadosusuario',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
    ]
