# Generated by Django 2.1.15 on 2020-08-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programacionbck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP_No_modificar', models.CharField(blank=True, db_column='IP', editable=False, max_length=50, null=True)),
                ('Server_Name_No_modificar', models.CharField(blank=True, db_column='SERVER_NAME', editable=False, max_length=50, null=True)),
                ('Lunes_a_Sábado', models.IntegerField(blank=True, db_column='CANT_L_S', null=True)),
                ('Domingo', models.IntegerField(blank=True, db_column='CANT_DMG', null=True)),
                ('Mensual', models.IntegerField(blank=True, db_column='CANT_MENSUAL', null=True)),
            ],
            options={
                'verbose_name': 'Programación',
                'verbose_name_plural': 'Programación copias diarias por instancia',
                'db_table': 'programacionBck',
                'ordering': ['Server_Name_No_modificar'],
                'managed': False,
            },
        ),
    ]
